### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Jantje19**
Is this what you ment with [this](https://codein.withgoogle.com/tasks/4745326489501696/)?

### CODE REVIEW

**Comment by matiasbaez** [comment]
Almost, but it would be great if you could specify the amount used to
reach that amount.

For instance:

614 Dollars (Random Number)

6 billetes of 100 dollars
1 billete of 10 dollars
2 billetes of 2 dollars

2016-12-02 12:59 GMT-03:00, Vic <notifications@github.com>:

**Comment by Jantje19** [comment]
I've added the option that specifies the amount used to reach the ranom amount.

**Comment by matiasbaez** [comment]
Yes, you will add it. Remember that the activity is for Sugar, and your
message with console.log don't look at in the activity.

El 2/12/2016 14:12, "Vic" <notifications@github.com> escribió:

I've added the option that specifies the amount used to reach the ranom
amount.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/matiasbaez/Changes-GCI-2016/pull/1#issuecomment-264507690>,
or mute the thread

**Comment by matiasbaez** [comment]
Send the github url and give him to in send to review.

**Comment by Jantje19** [comment]
Hi, I don't really understand what you're saing. Which GitHub URL do I have to give?

**Comment by matiasbaez** [comment]
The link of the changes on GitHub.

El 2/12/2016 17:28, "Vic" <notifications@github.com> escribió:

Hi, I don't really understand what you're saing. Which GitHub URL do I have
to give?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/matiasbaez/Changes-GCI-2016/pull/1#issuecomment-264554584>,
or mute the thread

**Comment by Jantje19** [comment]
Oh, [this](https://github.com/Jantje19/Changes-GCI-2016)?

**Comment by matiasbaez** [comment]
Yes

**Pull request closed without merging**
